In [1]:
# schedule extractor

import re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import pandas as pd

driver = webdriver.Chrome()
link = r"https://aisis.ateneo.edu/j_aisis/J_VMCS.do"

driver.get(link)
time.sleep(1)

driver.find_element(By.NAME, 'userName').send_keys("236842") #lmao i almost left my password in
driver.find_element(By.NAME, 'password').send_keys("spyuaisis1")
driver.find_element(By.NAME, "submit").click()
time.sleep(1)

driver.find_element(By.XPATH, '//a[contains(@href, "J_VMCS.do")]').click()
time.sleep(1.5)

soup = BeautifulSoup(driver.page_source, 'html.parser')
driver.quit()

# find the table with the schedule
all_tables = soup.find_all("table")
schedule_table = None
for table in all_tables:
    # check for presence of headers or specific keywords in table cells
    if any("Time" in cell.text.strip() for cell in table.find_all("td")[:2]):
        schedule_table = table
        break

# extract data from the table and load it into dataframe
rows = schedule_table.find_all("tr") # all rows are indicated by "tr" when printing the extracted soup
data = [] # initializing
headers = [header.text.strip() for header in rows[0].find_all("td")]
# rows[0] accesses the first row, which for this soup object contains all the table headers 'Time', 'Mon, 'Tue', 'Wed', etc.
# find_all("td") finds all the column elements inside this header row
# header.text.strip() extracts the text, removes any whitespace, and stores the text it extracts as headers for the df

for row in rows[1:]:
    # we skip the header row since it's already been skimmed over
    cols = row.find_all("td")
    # finding all the column elements across all rows barring the header row
    data.append([col.text.strip() for col in cols])

df = pd.DataFrame(data, columns=headers)

# display dataframe
df

,Time,Mon,Tue,Wed,Thur,Fri,Sat
0,700-730,,,,,,
1,730-800,,,,,,
2,800-830,,,,,,
3,830-900,,,,,,
4,900-930,,,,,,
5,930-1000,,,,,,
6,1000-1030,,,,,,
7,1030-1100,,,,,,
8,1100-1130,,,,,,
9,1130-1200,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),,,,
10,1200-1230,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),
11,1230-1300,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),
12,1300-1330,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),
13,1330-1400,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),
14,1400-1430,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),
15,1430-1500,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),
16,1500-1530,,,,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),
17,1530-1600,,,,ArtAp 10J INNOVATION 202 (FULLY ONSITE),ITMGT 25.03N SEC-A123 (FULLY ONSITE),
18,1600-1630,,,,,,
19,1630-1700,,,,,,
20,1700-1730,,,,,,
21,1730-1800,,,,,,
22,1800-1830,,,,,,
23,1830-1900,,,,,,
24,1900-1930,,,,,,
25,1930-2000,,,,,,
26,2000-2030,,,,,,
27,2030-2100,,,,,,
28,2100-2130,,,,,,

In [3]:
# panda extractor
def panda_schedule_extractor(df):
    schedules = []
    days = df.columns[1:]  # excluding the column for 'Time' to store the names of the days

    for day in days:
        current_class = None # initializing current_class and start_time as None
        start_time = None
        for index, row in df.iterrows(): # iterates over each row in the DataFrame
            time = row['Time'] # stores the current time range from column 'Time'
            class_name = row[day] # stores the class name for the current 'day'

            if class_name and class_name != current_class: # if class_name exists (not empty) and it's different from the current_class, the program reads it as a new class starting
                if current_class: # if there's an ongoing class, it still occupies the current time slot
                    end_time = df.at[index-1, 'Time'].split('-')[1] #the end time of the current class is the end time of the previous time slot (hence index-1) 
                    schedules.append(f"{current_class} {current_day} {start_time}-{end_time}") #all this is appended to the schedule string here
                current_class = class_name # the current_class is updated to the new name of the new class
                current_day = day # current_day is updated to the day of the new class
                start_time = time.split('-')[0] # start time is set to the start time of the current time_slot
            elif class_name != current_class: # this elif-if checks if an ongoing class is about to end
                if current_class: # if there's an ongoing class and class_name 
                    end_time = df.at[index-1, 'Time'].split('-')[1] 
                    schedules.append(f"{current_class} {current_day} {start_time}-{end_time}")
                current_class = None

        # Handle the last ongoing class of the day
        if current_class:
            end_time = time.split('-')[1] # end time of the last ongoing class is the end time of the current time slot
            schedules.append(f"{current_class} {current_day} {start_time}-{end_time}")

    return schedules

# Extract schedules
class_schedules = panda_schedule_extractor(df)
for schedule in class_schedules:
    print(schedule)

ArtAp 10J INNOVATION 202 (FULLY ONSITE) Mon 1130-1500
ITMGT 25.03N SEC-A123 (FULLY ONSITE) Tue 1130-1500
ArtAp 10J INNOVATION 202 (FULLY ONSITE) Thur 1200-1600
ITMGT 25.03N SEC-A123 (FULLY ONSITE) Fri 1200-1600